DROP TABLE IF EXISTS test_tags;
DROP TABLE IF EXISTS test_items;

CREATE TABLE test_items (
    id SERIAL PRIMARY KEY,
    creation_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    age INTEGER DEFAULT 0,
    role TEXT NOT NULL DEFAULT 'user'
);

CREATE TABLE test_tags (
    id SERIAL PRIMARY KEY,
    item_id INTEGER REFERENCES test_items(id) ON DELETE CASCADE,
    tag TEXT NOT NULL
);
